### ISSUE TITLE
shell-init: error

### ISSUE THREAD

**Issue by caltrop2075** [ascii-boxes/boxes#93] opened 2021-09-24 11:49 UTC
config
$BOXES not set
$HOME/.boxes
/etc/boxes/boxes-config

ERROR using $HOME/.boxes configuration
boxes version 1.3 ()

what's in the Mint/Ubuntu repository
I have been finding a LOT of unstable apps in the repository
very badly maintained anymore

unless there's a PPA with newer versions I'm NOT compiling it on my system
I'll just write my own code in that case
good luck with this

$HOME/.boxes:
# my boxes
# ------------------------------------------------------------------------------

BOX cdash

sample
    /*-----------*/
    /*           */
    /*           */
    /*-----------*/
ends

shapes {
    nw ("/*") n ("-") ne ("*/")
     w ("/*")          e ("*/")
    sw ("/*") s ("-") se ("*/")
}

delim ?"
replace "\*/" with "*\/"               # quote closing comment tags
reverse "\*\\/" to "*/"

padding {
    horiz 1             # alternatives: all, vert, lef, rig, bottom, top
}                       # can be combined, e.g. all 3 top 1

elastic (n,e,s,w)

END cdash

# ------------------------------------------------------------------------------

SCRIPT:
#!/bin/bash
clear

str="Test ASCII Boxes\ndefault to C box\ntest\nthis"

echo -e "$str" | boxes -d "cdash"

OUTPUT:
/*------------------*/
/* Test ASCII Boxes */
/* default to C box */
/* test             */
/* this             */
/*------------------*/
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory

**Comment by caltrop2075** [comment] 2021-09-24 11:51
FYI   system

viewed best with monospace font

            OS Linux Mint 20.1 x86_64
          Host Latitude E5570
        Kernel Linux 5.4.0-86-generic
        Uptime 48 mins
      Packages 3533 (dpkg), 11 (flatpak)
         Shell bash 5.0.17
    Resolution 1366x768, 1920x1080
            DE MATE
            WM Metacity (Marco)
      WM Theme Material-Black-Lime-3.38
         Theme Material-Black-Lime-3.38 [GTK2/3]
         Icons mate [GTK2/3]
      Terminal mate-terminal
 Terminal Font Monospace 10
           CPU Intel i5-6440HQ (4) @ 3.500GHz
           GPU Intel HD Graphics 530
        Memory 884MiB / 7636MiB

**Comment by tsjensen** [comment] 2021-09-24 13:37
Interesting observation.  
Googling the warning message gave me [this SO post](https://stackoverflow.com/q/29396928/1005481). This makes me believe it's more of a shell issue than a *boxes* issue.  
May I ask you to tell us how these suggestions worked for you?

**Comment by caltrop2075** [comment] 2021-09-26 10:16
???

just running from my $HOME directory with $PATH to $HOME/bin

only thing is I used .boxes custom config

oh well... I wrote an awk script that does boxing, not as fancy as boxes
and no error messages

been having issues with Mint lately, things have changed since 18.1 and
it's not good


Liz 😼
Enjoy The Collapse
🤪🔥💥💀

**Comment by tsjensen** [comment] 2021-09-26 12:10
Well, I ran your script with your config and it worked perfectly fine. Also, the warning you are getting is really caused by the inode switch - I would know of nothing else that can trigger this message at the moment.

Since you have your awk script now, I am closing this issue. Do feel free to reopen it anytime if new data comes up which may help us improve boxes. Thanks!

**Closed by tsjensen** 2021-09-26 12:10 UTC
