### ISSUE TITLE
Compilation on Arch Linux

### ISSUE THREAD

**Issue by aKriJcz** [ascii-boxes/boxes#26] opened 2016-01-03 15:43 UTC
Hello,

I have problem compiling boxes on Arch Linux. Error message is:
```
| For compilation info please refer to the boxes compilation FAQ
| at http://boxes.thomasjensen.com/docs/faq.html#q5
sed -e 's/--BVERSION--/1.1.3-SNAPSHOT/; s/--GLOBALCONF--/\/usr\/share\/boxes/' src/boxes.h.in > src/boxes.h
sed -e 's/--BVERSION--/1.1.3-SNAPSHOT/; s/--GLOBALCONF--/\/usr\/share\/boxes/' doc/boxes.1.in > doc/boxes.1
make -C src BOXES_PLATFORM=unix build
make[1]: Entering directory '/home/jirka/tmp/boxes/boxes/src'
make BOXES_PLATFORM=unix ALL_OBJ="parser.o lex.yy.o boxes.o tools.o shape.o generate.o remove.o" CFLAGS_ADDTL="-O " STRIP=true flags_unix boxes
make[2]: Entering directory '/home/jirka/tmp/boxes/boxes/src'
make[2]: Nothing to be done for 'flags_unix'.
bison -o parser.c -d parser.y
gcc -ansi -I. -Iregexp -Wall -W -O    -c -o parser.o parser.c
flex -t lexer.l > lexer.tmp.c
echo '#include "config.h"' > lex.yy.c
cat lexer.tmp.c >> lex.yy.c
rm lexer.tmp.c
gcc -ansi -I. -Iregexp -Wall -W -O    -c -o lex.yy.o lex.yy.c
<stdout>: In function 'yy_get_next_buffer':
<stdout>:1705:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
<stdout>: In function 'yyensure_buffer_stack':
<stdout>:2102:21: error: C++ style comments are not allowed in ISO C90
<stdout>:2102:21: error: (this will be reported only once per input file)
lexer.l: At top level:
<stdout>:1800:16: warning: 'input' defined but not used [-Wunused-function]
<builtin>: recipe for target 'lex.yy.o' failed
make[2]: *** [lex.yy.o] Error 1
make[2]: Leaving directory '/home/jirka/tmp/boxes/boxes/src'
Makefile:49: recipe for target 'build' failed
make[1]: *** [build] Error 2
make[1]: Leaving directory '/home/jirka/tmp/boxes/boxes/src'
Makefile:37: recipe for target 'build' failed
make: *** [build] Error 2
```

I'm not C expert but I think that problem may be caused by compiling with `-ansi` flag which is probably set in file src/Makefile in target `flags_unix`. Or I have something wrong with my system. I am using GCC 5.3.0. Thanks.

**Comment by tsjensen** [comment] 2016-01-03 20:09
I have no ArchLinux available to reproduce, unfortunately.
Have you tried the [compilation FAQ](http://boxes.thomasjensen.com/docs/faq.html#q5)? You may try setting `-traditional`, and/or removing `-ansi`.
When you get it to work, please be sure to tell us how, so we can add that information to the documentation or even the Makefiles. Thanks!

**Comment by tsjensen** [comment] 2016-01-07 12:55
I may switch to a CMake based build in the future. A sneak preview of the current draft is available on a [feature branch](https://github.com/ascii-boxes/boxes/tree/cmake). You may want to try building that if CMake is available on your platform.

**Comment by carnil** [comment] 2016-01-31 21:13
Hi!

The problem is as well reproducible on a Debian sid with flex 2.6.0.

it is actually a bug in flex, which prevents to compiling with gcc -std=c89:

https://bugs.debian.org/813256

Regards

**Comment by tsjensen** [comment] 2016-02-02 13:32
Thank you @carnil for pointing us to the root cause!
This bug has been fixed in Flex, and work is currently being performed to include in Debian also. So in time, the problem should be solved.
**Question:** Do we have a workaround for the time being, or should be wait it out?

**Comment by tsjensen** [comment] 2016-02-05 17:05
Closing this issue, as it is not a *boxes* problem, and there is nothing else we can do about it except wait for the flex fix to propagate downstream.

**Closed by tsjensen** 2016-02-05 17:05 UTC
